package com.msadraii.multidex;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table COLOR_CODE.
 */
public class ColorCode {

    private Long id;
    private String argb;
    private String task;

    public ColorCode() {
    }

    public ColorCode(Long id) {
        this.id = id;
    }

    public ColorCode(Long id, String argb, String task) {
        this.id = id;
        this.argb = argb;
        this.task = task;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getArgb() {
        return argb;
    }

    public void setArgb(String argb) {
        this.argb = argb;
    }

    public String getTask() {
        return task;
    }

    public void setTask(String task) {
        this.task = task;
    }

}
