package com.msadraii.multidex;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.msadraii.multidex.ColorCode;
import com.msadraii.multidex.Entry;

import com.msadraii.multidex.ColorCodeDao;
import com.msadraii.multidex.EntryDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig colorCodeDaoConfig;
    private final DaoConfig entryDaoConfig;

    private final ColorCodeDao colorCodeDao;
    private final EntryDao entryDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        colorCodeDaoConfig = daoConfigMap.get(ColorCodeDao.class).clone();
        colorCodeDaoConfig.initIdentityScope(type);

        entryDaoConfig = daoConfigMap.get(EntryDao.class).clone();
        entryDaoConfig.initIdentityScope(type);

        colorCodeDao = new ColorCodeDao(colorCodeDaoConfig, this);
        entryDao = new EntryDao(entryDaoConfig, this);

        registerDao(ColorCode.class, colorCodeDao);
        registerDao(Entry.class, entryDao);
    }
    
    public void clear() {
        colorCodeDaoConfig.getIdentityScope().clear();
        entryDaoConfig.getIdentityScope().clear();
    }

    public ColorCodeDao getColorCodeDao() {
        return colorCodeDao;
    }

    public EntryDao getEntryDao() {
        return entryDao;
    }

}
