package com.msadraii.multidex;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.msadraii.multidex.Label;
import com.msadraii.multidex.Entry;

import com.msadraii.multidex.LabelDao;
import com.msadraii.multidex.EntryDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig labelDaoConfig;
    private final DaoConfig entryDaoConfig;

    private final LabelDao labelDao;
    private final EntryDao entryDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        labelDaoConfig = daoConfigMap.get(LabelDao.class).clone();
        labelDaoConfig.initIdentityScope(type);

        entryDaoConfig = daoConfigMap.get(EntryDao.class).clone();
        entryDaoConfig.initIdentityScope(type);

        labelDao = new LabelDao(labelDaoConfig, this);
        entryDao = new EntryDao(entryDaoConfig, this);

        registerDao(Label.class, labelDao);
        registerDao(Entry.class, entryDao);
    }
    
    public void clear() {
        labelDaoConfig.getIdentityScope().clear();
        entryDaoConfig.getIdentityScope().clear();
    }

    public LabelDao getLabelDao() {
        return labelDao;
    }

    public EntryDao getEntryDao() {
        return entryDao;
    }

}
