package com.sadraii.hyperdex;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table COLOR_CODE.
 */
public class ColorCode {

    private Long id;
    private Long tag;
    private String argb;
    private String task;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public ColorCode() {
    }

    public ColorCode(Long id) {
        this.id = id;
    }

    public ColorCode(Long id, Long tag, String argb, String task) {
        this.id = id;
        this.tag = tag;
        this.argb = argb;
        this.task = task;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getTag() {
        return tag;
    }

    public void setTag(Long tag) {
        this.tag = tag;
    }

    public String getArgb() {
        return argb;
    }

    public void setArgb(String argb) {
        this.argb = argb;
    }

    public String getTask() {
        return task;
    }

    public void setTask(String task) {
        this.task = task;
    }

    // KEEP METHODS - put your custom methods here
    // TODO: remove this
//    /**
//     * Constructor without tag field, as it is auto-incremented.
//     *
//     * @param id
//     * @param argb
//     * @param task
//     */
//    public ColorCode(Long id, String argb, String task) {
//        this.id = id;
//        this.argb = argb;
//        this.task = task;
//    }
    // KEEP METHODS END

}
